name: Website Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Run Website Deployment
        run: echo "running website deployment"

  test:
    needs: deployment
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_DEPLOY_TEST_TRIGGER_APP_ID }}
          private-key: ${{ secrets.GH_DEPLOY_TEST_TRIGGER_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Run Playwright Test Suite
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh api -X POST /repos/jpuckett-di/di-website-deployment-test-playwright-test/actions/workflows/daily-deploy-test.yml/dispatches \
            --input - <<< '{"ref": "main"}'
